# Use official Node.js image as a base
FROM node:18.18.0

# Set the working directory
WORKDIR /app

# Copy package.json and lock file
COPY package*.json yarn.lock ./

# Install dependencies
RUN yarn install

# Copy the rest of the application
COPY . ./

# Expose the application port
EXPOSE 3000

# Run the application
CMD ["sh", "-c", "yarn start:dev"]
